import 'package:pluto_grid/pluto_grid.dart';

const consfiguracaoPlutoGrid = PlutoGridConfiguration(
  localeText: PlutoGridLocaleText(
    unfreezeColumn: 'Desfixar',
    freezeColumnToEnd: 'Fixar a esquerda',
    freezeColumnToStart: 'Fixar a direita',
    autoFitColumn: 'Auto ajustar',
    hideColumn: 'Esconder coluna',
    setColumns: 'Definir coluna',
    setFilter: 'Definir filtro',
    resetFilter: 'Ressetar filtro',
    setColumnsTitle: 'Nome da Coluna',
    filterColumn: 'Coluna',
    filterType: 'Tipo',
    filterValue: 'Valor',
    filterAllColumns: 'Todas as colunas',
    filterContains: 'Contém',
    filterEquals: 'Igual a',
    filterStartsWith: 'Iniciar com',
    filterEndsWith: 'Terminar com',
    filterGreaterThan: 'Maior que',
    filterGreaterThanOrEqualTo: 'Greater than or equal to',
    filterLessThan: 'Less than',
    filterLessThanOrEqualTo: 'Less than or equal to',
    sunday: 'Dom',
    monday: 'Seg',
    tuesday: 'Ter',
    wednesday: 'Qua',
    thursday: 'Qui',
    friday: 'Sex',
    saturday: 'Sáb',
    hour: 'Hora',
    minute: 'Minuto',
    loadingText: 'Carregando...',
  ),
);
